server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Prevent port leaking in any redirects
    absolute_redirect off;

    location / {
        try_files $uri $uri/index.html $uri/ /index.html;
    }
}
